layout: {qmk_keyboard: corne_rotated, qmk_layout: LAYOUT_split_3x6_3}
layers:
  default:
  - [TAB, Q, W, E, R, T, Y, U, I, O]
  - - P
    - BSPC
    - {t: ESC, h: LCTRL}
    - {t: A, h: LCTRL}
    - {t: S, h: LALT}
    - {t: D, h: LGUI}
    - {t: F, h: LSHFT}
    - G
    - H
    - {t: J, h: RSHFT}
  - - {t: K, h: RGUI}
    - {t: L, h: RALT}
    - {t: ;, h: RCTRL}
    - ''''
    - LSHFT
    - Z
    - X
    - C
    - V
    - B
  - [N, M, ',', ., /, RSHFT, LGUI, lower, BACKSPACE, RET]
  - - {t: SPACE, h: raise}
    - RALT
  lower:
  - - {t: ▽, type: trans}
    - '1'
    - '2'
    - '3'
    - '4'
    - '5'
    - '6'
    - '7'
    - '8'
    - '9'
  - - '0'
    - {t: ▽, type: trans}
    - {t: ▽, type: trans}
    - {t: ▽, type: trans}
    - {t: ▽, type: trans}
    - {t: ▽, type: trans}
    - {t: ▽, type: trans}
    - {t: ▽, type: trans}
    - LEFT
    - DOWN
  - - UP
    - RIGHT
    - {t: ▽, type: trans}
    - {t: ▽, type: trans}
    - {t: ▽, type: trans}
    - {t: ▽, type: trans}
    - {t: ▽, type: trans}
    - {t: ▽, type: trans}
    - {t: ▽, type: trans}
    - {t: ▽, type: trans}
  - - {t: ▽, type: trans}
    - {t: ▽, type: trans}
    - {t: ▽, type: trans}
    - {t: ▽, type: trans}
    - {t: ▽, type: trans}
    - {t: ▽, type: trans}
    - {t: ▽, type: trans}
    - {type: held}
    - {t: ▽, type: trans}
    - {t: ▽, type: trans}
  - - {t: ▽, type: trans}
    - {t: ▽, type: trans}
  raise:
  - - {t: ▽, type: trans}
    - '!'
    - '@'
    - '#'
    - $
    - '%'
    - ^
    - '&'
    - '*'
    - (
  - - )
    - {t: ▽, type: trans}
    - LCTRL
    - {t: ▽, type: trans}
    - {t: ▽, type: trans}
    - {t: ▽, type: trans}
    - {t: ▽, type: trans}
    - {t: ▽, type: trans}
    - '-'
    - '='
  - - '['
    - ']'
    - \
    - '`'
    - {t: ▽, type: trans}
    - {t: ▽, type: trans}
    - {t: ▽, type: trans}
    - {t: ▽, type: trans}
    - {t: ▽, type: trans}
    - {t: ▽, type: trans}
  - - _
    - +
    - '{'
    - '}'
    - '|'
    - '~'
    - {t: ▽, type: trans}
    - {t: ▽, type: trans}
    - {t: ▽, type: trans}
    - {t: ▽, type: trans}
  - - {type: held}
    - {t: ▽, type: trans}
  zmk:
  - - {t: ▽, type: trans}
    - {t: ▽, type: trans}
    - {t: ▽, type: trans}
    - {t: ▽, type: trans}
    - {t: ▽, type: trans}
    - {t: ▽, type: trans}
    - {t: ▽, type: trans}
    - {t: ▽, type: trans}
    - {t: ▽, type: trans}
    - {t: ▽, type: trans}
  - - {t: ▽, type: trans}
    - {t: ▽, type: trans}
    - BT CLR
    - {t: BT, h: '0'}
    - {t: BT, h: '1'}
    - {t: BT, h: '2'}
    - {t: BT, h: '3'}
    - {t: BT, h: '4'}
    - SOFT OFF
    - EP TOG
  - - RESET
    - '&macro_ver'
    - {t: ▽, type: trans}
    - {t: ▽, type: trans}
    - BOOT
    - {t: ▽, type: trans}
    - {t: ▽, type: trans}
    - {t: ▽, type: trans}
    - {t: ▽, type: trans}
    - {t: ▽, type: trans}
  - - {t: ▽, type: trans}
    - {t: ▽, type: trans}
    - {t: ▽, type: trans}
    - {t: ▽, type: trans}
    - {t: ▽, type: trans}
    - BOOT
    - {t: ▽, type: trans}
    - {type: held}
    - {t: ▽, type: trans}
    - {t: ▽, type: trans}
  - - {type: held}
    - {t: ▽, type: trans}
combos:
- p: [37, 40]
  k: zmk
  l: [default]
